### ISSUE TITLE
What are the commands for the Achievements system to add your own achievement?

### ISSUE THREAD

**Issue by OctaTV** [GanstaKingofSA/DDLCModTemplate2.0#26]
Hi there! Sorry if I sound kinda rude but I don't understand the system for the Achievements in the DDLC Mod Template. Can you explain to me how to make the achievements? How to make an achievements at a certain point of the story?
Thank you

**Comment by GanstaKingofSA** [comment]
A guide for the achievements is coming soon as many are reporting some confusion with the features despite the comments but a brief run-down is such:

To make an achievement, you will need to make a variable and create a new Achievements class for it using the information you want to use in particular. Here is how it should look for a regular achievement.
```py
example = Achievements("Name of the Achievement", "Description of the Achievement",
            "path/to/achievements_image.png", "Persistent Variable Name tied to the Achievement")
achievementList.append(example)
```
If you are making a achievement that requires a certain value in order to reach:
```py
example = Achievements("Name of the Achievement", "Description of the Achievement",
            "path/to/achievements_image.png", "Persistent Variable Name tied to the Achievement", True, Max Number Required for the Achievement)
achievementList.append(example)
```
It is very important that achievementList.append(example) comes after your achievement declaration variable as it will not show up on the Achievements page if you don’t do so.

Example:
```py
example = Achievements("Special Scene", "You seen something you weren’t supposed to normally see, but it’s something special.",
            "mod_assets/special_scene_achievement.png", "persistent.special_scene_seen")
achievementList.append(example)
```

**Comment by GanstaKingofSA** [comment]
Also the Issues tab is mainly for template bugs or possible features to be added, rather than questions. I might see how to get Github discussions working soon for such.
